#
# Set up for an Avatar (bending) server.
#

# This is a modifier on the default survival configs
inherit: survival

# Include only survival spells, but disable them so we can inherit without them being available
include_inherited:
  - spells
  - icons
disable_inherited:
 - spells

# Don't allow crafting
enable_crafting: false

# Configure some custom damage types
damage_types:
  earth:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10
  fire:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10
  air:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10
  water:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10

# Default class
default_mage_class: bender
