# This is a modifier on the default survival configs
inherit: survival

include_inherited:
 - spells
 - icons

# Set this to true to add the cooldown timers on skills
# This will involve scanning players' hotbars all the time, even
# when not holding wands.
live_hotbar_skills: true

# Turn off cast messages, let Heroes handle messaging
show_cast_messages: false

# We use skull icons here since the spell items interfere with Heroes
url_icons_enabled: true

# Use the flat skull RP if you're using skull icons
default_resource_pack: "http://rp.elmakers.com/flat-skulls.zip"

# The chances of this RP ever updating are very slim, so skip checking for updates
resource_pack_check_interval: 0

# We don't want spells to level up since that won't work well with Heroes skills overriding
# spell parameters
enable_automatic_spell_upgrades: false

# Disable SP system
sp_enabled: false

# Use this to prefix skills added via the Magic skill pack
# This can be used to avoid conflicts with public or other skill
# You can also rename individual spells by adding something like
# blink:
#    name: Teleport
# to Magic's spells.yml
heroes_skill_prefix: ""

# Turn this off if you don't want crafting of the Heroes wand
# enable_crafting: false

# Skip loading configs if you want
# Though you may want to keep wands for the Heroes wand
# and spells for the Heroes skill pack, available at
# http://rp.elmakers.com/MagicHeroesSkills.zip
# load_default_wands: false
# load_default_paths: false
# load_default_spells: false
# load_default_items: false
# load_default_mobs: false

# Use this to turn off disabled icon URLs when using skull icons
# disabled_icon_url: ""

# Use this to change where spells originate from
# This effects visual effects as well as actual projectile source locations.
# The defaults source from the main hand.
# The default cast location if not holding a wand. Options are "mainhand", "offhand" and "eyes"
# default_cast_location: mainhand

# This offsets left or right from the center of the body
# default_cast__location_offset: 0.5

# This offsets from the eyes
# default_cast__location_offset_vertical: -0.4

